USE ROLE ACCOUNTADMIN;

SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE ANALYST_ROLE;

-- Grant roles to yourself

GRANT ROLE ANALYST_ROLE TO ROLE SYSADMIN;
GRANT ROLE ANALYST_ROLE TO USER IDENTIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE ANALYST_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE ANALYST_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE ANALYST_ROLE;


-- Databases
CREATE OR REPLACE DATABASE FP_DB;
GRANT OWNERSHIP ON DATABASE FP_DB TO ROLE ANALYST_ROLE;

-- Warehouses
CREATE OR REPLACE WAREHOUSE FP_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE FP_WH TO ROLE ANALYST_ROLE;

-- Schemas
CREATE OR REPLACE SCHEMA FP_DB.DATASETS_1;
GRANT OWNERSHIP ON SCHEMA FP_DB.DATASETS_1 TO ROLE ANALYST_ROLE;
CREATE OR REPLACE SCHEMA FP_DB.DATASETS_2;
GRANT OWNERSHIP ON SCHEMA FP_DB.DATASETS_2 TO ROLE ANALYST_ROLE;

GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE FP_DB TO ROLE ANALYST_ROLE;
GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN DATABASE FP_DB TO ROLE ANALYST_ROLE;
GRANT ALL PRIVILEGES ON ALL STAGES IN DATABASE FP_DB TO ROLE ANALYST_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE FP_DB TO ROLE ANALYST_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE FP_DB TO ROLE ANALYST_ROLE;
GRANT ALL PRIVILEGES ON ALL TASKS IN DATABASE FP_DB TO ROLE ANALYST_ROLE;
