USE ROLE ACCOUNTADMIN;

SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE ANALYST_ROLE;

-- Grant roles to yourself

GRANT ROLE ANALYST_ROLE TO ROLE SYSADMIN;
GRANT ROLE ANALYST_ROLE TO USER IDENTIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE ANALYST_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE ANALYST_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE ANALYST_ROLE;


-- Databases
CREATE OR REPLACE DATABASE FP_DB;
GRANT OWNERSHIP ON DATABASE FP_DB TO ROLE ANALYST_ROLE;

-- Warehouses
CREATE OR REPLACE WAREHOUSE FP_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE FP_WH TO ROLE ANALYST_ROLE;